runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

handlers:
- url: /
  script: main.app

- url: /api
  script: main.app

- url: /static
  static_dir: static